// Code generated by MockGen. DO NOT EDIT.
// Source: ./type.go
//
// Generated by this command:
//
//	mockgen -source=./type.go -destination=../../mocks/llm.mock.go -package=llmmocks -typed=true Service
//

// Package llmmocks is a generated GoMock package.
package llmmocks

import (
	context "context"
	reflect "reflect"

	domain "gitee.com/flycash/ai-gateway-demo/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// Stream mocks base method.
func (m *MockService) Stream(ctx context.Context, req domain.Request) (chan domain.StreamEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stream", ctx, req)
	ret0, _ := ret[0].(chan domain.StreamEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Stream indicates an expected call of Stream.
func (mr *MockServiceMockRecorder) Stream(ctx, req any) *MockServiceStreamCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stream", reflect.TypeOf((*MockService)(nil).Stream), ctx, req)
	return &MockServiceStreamCall{Call: call}
}

// MockServiceStreamCall wrap *gomock.Call
type MockServiceStreamCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceStreamCall) Return(arg0 chan domain.StreamEvent, arg1 error) *MockServiceStreamCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceStreamCall) Do(f func(context.Context, domain.Request) (chan domain.StreamEvent, error)) *MockServiceStreamCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceStreamCall) DoAndReturn(f func(context.Context, domain.Request) (chan domain.StreamEvent, error)) *MockServiceStreamCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
