// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package startup

import (
	"gitee.com/flycash/ai-gateway-demo/internal/grpc"
	"gitee.com/flycash/ai-gateway-demo/internal/mocks"
)

// Injectors from wire.go:

func InitServer(service *llmmocks.MockService) *grpc.LLMServiceServer {
	llmService := InitService(service)
	llmServiceServer := grpc.NewLLMServiceServer(llmService)
	return llmServiceServer
}
